version: '1.0'
stages:
  - checkout
  - prepare   
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    stage: checkout
    type: git-clone
    repo: 'dAmarender/terraform-vm-instance'
    revision: master
    git: github      
  SetupAuth:
    image: alpine:3.9
    title: Setting up Google cloud auth
    stage: prepare
    commands:
      - echo $ACCOUNT_JSON_CONTENT 
      - cf_export GOOGLE_CLOUD_KEYFILE_JSON
  DeployWithTerraform:
    image: hashicorp/terraform:1.4.6
    title: Deploying Terraform plan
    stage: deploy
    commands:
      - terraform -version
      - terraform init
      - terraform plan 
  
